/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hritserver_HritFormatter */

#ifndef _Included_hritserver_HritFormatter
#define _Included_hritserver_HritFormatter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hritserver_HritFormatter
 * Method:    format
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Lhritserver/json/JSONResponse;)I
 */
JNIEXPORT jint JNICALL Java_hritserver_HritFormatter_format
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
