/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calliope_AeseFormatter */

#ifndef _Included_calliope_AeseFormatter
#define _Included_calliope_AeseFormatter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calliope_AeseFormatter
 * Method:    format
 * Signature: ([C[Ljava/lang/String;[Ljava/lang/String;Lcalliope/json/JSONResponse;)I
 */
JNIEXPORT jint JNICALL Java_calliope_AeseFormatter_format
  (JNIEnv *, jobject, jcharArray, jobjectArray, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
