/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calliope_AustESEFormatter */

#ifndef _Included_calliope_AustESEFormatter
#define _Included_calliope_AustESEFormatter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calliope_AustESEFormatter
 * Method:    format
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Lcalliope/json/JSONResponse;)I
 */
JNIEXPORT jint JNICALL Java_calliope_AustESEFormatter_format
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
