/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calliope_AustESEStripper */

#ifndef _Included_calliope_AustESEStripper
#define _Included_calliope_AustESEStripper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calliope_AustESEStripper
 * Method:    strip
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcalliope/JSONResponse;Lcalliope/JSONResponse;)I
 */
JNIEXPORT jint JNICALL Java_calliope_AustESEStripper_strip
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     calliope_AustESEStripper
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_calliope_AustESEStripper_version
  (JNIEnv *, jobject);

/*
 * Class:     calliope_AustESEStripper
 * Method:    formats
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_calliope_AustESEStripper_formats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
