/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hritserver.tests;

/**
 * Strings to needed to run TestImage
 * @author desmond
 */
public class TestImageStrings 
{
    static String IMAGE_JS = 
    "$(document).ready(function()\n{\n\t$(\"span[id]\").each(\n\t\t"
    +"function()\n\t\t{\n\t\t\t$(this).bind('mouseover',function("
    +"){onMouseOver(this.id)});\n\t\t\t$(this).bind('mouseout',fun"
    +"ction(){onMouseOut()});\n\t\t}\n\t);\n}); \n$(function() \n{"
    +"\n\tscaleImage();\n\t$('#facsimile').maphilite({fade: false,"
    +"mouseEnter: onMouseEnter,mouseLeave: onMouseLeave});\n});";
    static String SCALE_IMAGE_SCRIPT = 
    "function getOffsetTopForElem( elem )\n{\n\tvar offset = 0;\n\t"
    +"while ( elem != null )\n\t{\n\t\toffset += elem.offsetTop;\n"
    +"\t\telem = elem.offsetParent;\n\t}\n\treturn offset;\n}\nfu"
    +"nction getBorderValue( elem, prop )\n{\n\tvar value = getSty"
    +"leValue( elem, prop );\n\tvar number = 0;\n\tif ( value )\n\t"
    +"{\n\t\tnumber = parseInt( value );\n\t\tif ( isNaN(number) "
    +")\n\t\t{\n\t\t\tif ( value == \"medium\" )\n\t\t\t\tnumber ="
    +" 3;\n\t\t\telse if ( value == \"thick\" )\n\t\t\t\tnumber = "
    +"6;\n\t\t\telse if ( value == \"thin\" )\n\t\t\t\tnumber = 1;"
    +"\n\t\t}\n\t}\n\treturn number;\n}\nfunction getWindowHeight("
    +")\n{\n\tvar myHeight = 0;\n\tif ( typeof( window.innerWidth "
    +") == 'number' )\n\t myHeight = window.innerHeight;\n\telse i"
    +"f ( document.documentElement\n\t\t&& ( document.documentElem"
    +"ent.offsetHeight ) )\n\t\t//IE 6+ in 'standards compliant mo"
    +"de'\n\t\tmyHeight = document.documentElement.offsetHeight;\n"
    +"\telse if ( document.body && document.body.offsetHeight )\n\t"
    +"\tmyHeight = document.body.offsetHeight;\n\treturn myHeight"
    +";\n}\nfunction cssToIE( prop )\n{\n\tvar parts = prop.split("
    +"\"-\");\n\tif ( parts.length > 0 )\n\t{\n\t\tvar ccProp = pa"
    +"rts[0];\n\t\tfor ( var i=1;i<parts.length;i++ )\n\t\t{\n\t\t"
    +"\tif ( parts[i].length > 0 )\n\t\t\t{\n\t\t\t\tccProp += par"
    +"ts[i].substr(0,1).toUpperCase()\n\t\t\t\t\t+parts[i].substr("
    +"1,parts[i].length-1);\n\t\t\t}\n\t\t}\n\t\treturn ccProp;\n\t"
    +"}\n\telse\n\t\treturn prop;\n}\nfunction getStyleValue( ele"
    +"m, prop )\n{\n\tvar value = getStyle( elem, prop );\n\tif ( "
    +"value )\n\t\treturn parseInt( value );\n\telse\n\t\treturn 0"
    +";\n}\nfunction getStyle( elem, prop )\n{\n\tif ( elem.curren"
    +"tStyle )\n\t\tvar y = elem.currentStyle[cssToIE(prop)];\n\te"
    +"lse if ( window.getComputedStyle )\n\t\tvar y = window.getCo"
    +"mputedStyle(elem,null)\n\t\t\t.getPropertyValue(prop);\n\tre"
    +"turn y;\n}\nfunction getFitHeight( elem )\n{\n\tvar topOffse"
    +"t = getOffsetTopForElem( elem );\n\tvar windowHeight = getWi"
    +"ndowHeight();\n\tvar vPadding = getStyleValue(elem,\"padding"
    +"-top\")\n\t\t+getStyleValue(elem,\"padding-bottom\");\n\tvar"
    +" vBorder = getBorderValue(elem,\"border-top-width\")\n\t\t+g"
    +"etBorderValue(elem,\"border-bottom-width\");\n\treturn windo"
    +"wHeight-(topOffset+vPadding+vBorder);\n}\nfunction scaleElem"
    +"ent( elem, attr, scale )\n{\n\tvar value = elem.getAttribute"
    +"(attr);\n\tvar values = value.split(\",\");\n\tvar newValue "
    +"= \"\";\n\tfor ( var i=0;i<values.length;i++ )\n\t{\n\t\tvar"
    +" intVal = parseInt( values[i] );\n\t\tintVal *= scale;\n\t\t"
    +"newValue += Math.round(intVal).toString();\n\t\tif ( i != va"
    +"lues.length-1 )\n\t\t\tnewValue += \",\";\n\t}\n\telem.setAt"
    +"tribute( attr, newValue );\n}\nfunction scaleMap( scale )\n{"
    +"\n\tvar map = document.getElementById(\"facsimileMap\");\n\t"
    +"var child = map.firstChild;\n\twhile ( child != null )\n\t{\n"
    +"\t\tif ( child.nodeType == Node.ELEMENT_NODE && child.nodeN"
    +"ame==\"AREA\" )\n\t\t\tscaleElement( child, \"coords\", scal"
    +"e );\n\t\tchild = child.nextSibling;\n\t}\n}\nfunction scale"
    +"Image()\n{\n\tvar img = document.getElementById(\"facsimile\""
    +");\n\tvar desHeight = getFitHeight( img );\n\tvar actHeight"
    +" = img.height;\n\tvar scale = desHeight/actHeight;\n\tscaleE"
    +"lement( img, \"width\", scale );\n\tscaleElement( img, \"hei"
    +"ght\", scale );\n\tscaleMap( scale );\n\tvar wrapper = img.p"
    +"arentNode;\n\twrapper.onscroll = scrollFunction;\n}\nfunctio"
    +"n checkBrowser()\n{\n\tif ( !Modernizr.backgroundsize )\n\t\t"
    +"alert(\"Warning: your browser is incompatible. \\nUse anoth"
    +"er like IE9+ Opera 10+ Safari 4+ FireFox 3.6+ Chrome 5+\");\n"
    +"}\nfunction do_popup1()\n{\n\tdocument.forms.default.submit"
    +"();\n}\nfunction replaceAttribute( elem, attr, prop, value )"
    +"\n{\n\tvar str = elem.getAttribute(attr);\n\tvar pos = -1;\n"
    +"\tif ( str )\n\t\tpos = str.indexOf(prop);\n\telse\n\t\tstr "
    +"= \"\";\n\tvar head = str;\n\tvar tail = \"\";\n\tif ( pos !"
    +"= -1 )\n\t{\n\t\thead = str.substr(0,pos);\n\t\ttail = str.s"
    +"ubstr(pos);\n\t\tvar pos2 = tail.indexOf(\";\");\n\t\tif ( p"
    +"os2 != -1 )\n\t\t\ttail = tail.substr(pos2);\n\t\telse\n\t\t"
    +"\ttail = \"\";\n\t}\n\telse\t if (str) // append\n\t\thead +"
    +"= \";\";\n\telem.setAttribute(attr, head+prop+\": \"+value+t"
    +"ail);\n}\nfunction scaleCanvas( image )\n{\n\tvar wrapper = "
    +"image.parentNode;\n\tvar canvas = image.previousSibling;\n\t"
    +"var newCanvas = document.createElement(\"canvas\");\n\tvar l"
    +"eft = \"left: \"+(wrapper.scrollLeft==0)?\"0\":\"-\"+wrapper"
    +".scrollLeft;\n\tvar top = \"top: \"+(wrapper.scrollTop==0)?\""
    +"0\":\"-\"+wrapper.scrollTop;\n\tnewCanvas.setAttribute(\"st"
    +"yle\",\"position: absolute;padding: 0;border: 0;\"+left+\";\""
    +"+top);\n\tnewCanvas.width = image.width;\n\tnewCanvas.heigh"
    +"t = image.height;\n\twrapper.replaceChild(newCanvas,canvas);"
    +"\n}\nfunction enlarge()\n{\n\tvar image = document.getElemen"
    +"tById(\"facsimile\");\n\tvar wrapper = image.parentNode;\n\t"
    +"var width = parseInt(image.width);\n\twidth *= 1.2;\n\timage"
    +".width = width.toString();\n\tvar height = parseInt(image.he"
    +"ight);\n\theight *= 1.2;\n\timage.height = height.toString()"
    +";\n\treplaceAttribute(wrapper,\"style\",\"background-size\","
    +"width.toString());\n\tscaleMap( 1.2 );\n\twrapper.onscroll=s"
    +"crollFunction;\n\t//scaleCanvas( image );\n}\nfunction shrin"
    +"k()\n{\n\tvar image = document.getElementById(\"facsimile\")"
    +";\n\tvar wrapper = image.parentNode;\n\tvar width = parseInt"
    +"(image.width);\n\twidth /= 1.2;\n\timage.width = width.toStr"
    +"ing();\n\tvar height = parseInt(image.height);\n\theight /= "
    +"1.2;\n\timage.height = height.toString();\n\treplaceAttribut"
    +"e(wrapper,\"style\",\"background-size\",width.toString());\n"
    +"\tscaleMap( 1/1.2 );\n\twrapper.onscroll=scrollFunction;\n\t"
    +"scaleCanvas( image );\n}\nfunction reset()\n{\n\tvar image ="
    +" document.getElementById(\"facsimile\");\n\timage.style.top="
    +"\"0px\";\n\timage.style.left=\"0px\";\n\timage.width=\"350\""
    +";\n\tvar wrapper = imgage.parentNode;\n\treplaceAttribute( w"
    +"rapper,\"style\",\"background-size\",image.width);\n\treplac"
    +"eAttribute( wrapper,\"style\",\"overflow\",\"hidden\");\n\tw"
    +"rapper.onscroll=scrollFunction;\n}\nfunction scrollFunction("
    +")\n{\n\tvar image = document.getElementById(\"facsimile\");\n"
    +"\tvar wrapper = image.parentNode;\n\tvar newPosition = \"-\""
    +"+wrapper.scrollLeft+\"px -\"+wrapper.scrollTop+\"px\";\n\tr"
    +"eplaceAttribute( wrapper,\"style\",\"background-position\",n"
    +"ewPosition );\n\tvar canvas = image.previousSibling;\n\trepl"
    +"aceAttribute( canvas, \"style\",\"left\",\"-\"+wrapper.scrol"
    +"lLeft.toString());\n\treplaceAttribute( canvas, \"style\",\""
    +"top\",\"-\"+wrapper.scrollTop.toString());\n}\nfunction onMo"
    +"useLeave( id )\n{\n\tvar span = document.getElementById(id);"
    +"\n\tif ( span )\n\t\tspan.setAttribute(\"style\",\"backgroun"
    +"d-color: white; border:0\");\n}\nfunction onMouseEnter( id )"
    +"\n{\n\tvar span = document.getElementById( id );\n\tif ( spa"
    +"n )\n\t\tspan.setAttribute(\"style\",\"background-color: rgb"
    +"a(255,0,0,0.4)\");\n}\nfunction onMouseOver( id )\n{\n\tvar "
    +"area = $(\"area[href='#\"+id+\"']\");\n\tif ( area )\n\t\t$."
    +"fn.maphilite.hiliteArea( area.get(0) );\n}\nfunction onMouse"
    +"Out()\n{\n\t$.fn.maphilite.clearArea();\n}";
    static String IMAGEMAP_D = 
    "<img id=\"facsimile\" src=\"/images/frontispiece3.jpg\" width"
    +"=\"2513\" height=\"3701\" border=\"0\" usemap=\"#frontispiec"
    +"e3\">\n<map id=\"facsimileMap\" name=\"frontispiece3\">\n<ar"
    +"ea shape=\"rect\" coords=\"986,397,1335,494\" onclick=\"this"
    +".style.background-color='red'\" href=\"#F1\">\n<area shape=\""
    +"rect\" coords=\"434,637,1476,783\" href=\"#F2\">\n<area sha"
    +"pe=\"rect\" coords=\"1476,636,1568,782\" href=\"#F3\">\n<are"
    +"a shape=\"rect\" coords=\"1568,637,1937,783\" href=\"#F4\">\n"
    +"<area shape=\"rect\" coords=\"371,783,1960,893\" href=\"#F5"
    +"\">\n<area shape=\"rect\" coords=\"371,893,1970,1006\" href="
    +"\"#F6\">\n<area shape=\"rect\" coords=\"371,1022,1965,1126\""
    +" href=\"#F7\">\n<area shape=\"rect\" coords=\"370,1153,1958,"
    +"1252\" href=\"#F8\">\n<area shape=\"rect\" coords=\"371,1275"
    +",1799,1376\" href=\"#F9\">\n<area shape=\"rect\" coords=\"37"
    +"1,1392,1950,1510\" href=\"#F10\">\n<area shape=\"rect\" coor"
    +"ds=\"369,1520,1950,1632\" href=\"#F11\">\n<area shape=\"rect"
    +"\" coords=\"365,1641,1584,1740\" href=\"#F12\">\n<area shape"
    +"=\"rect\" coords=\"368,1765,1938,1881\" href=\"#F14\">\n<are"
    +"a shape=\"rect\" coords=\"368,1889,990,1987\" href=\"#F15\">"
    +"\n<area shape=\"rect\" coords=\"435,2014,658,2102\" href=\"#"
    +"F17\">\n<area shape=\"poly\" coords=\"677,2054,678,2101,1490"
    +",2102,1488,2029,769,2027,753,2052\" href=\"#F19\">\n<area sh"
    +"ape=\"poly\" coords=\"1492,2049,1493,2099,1822,2100,1821,204"
    +"8\" href=\"#F21\">\n<area shape=\"rect\" coords=\"1829,2015,"
    +"1924,2101\" href=\"#F22\">\n<area shape=\"rect\" coords=\"37"
    +"2,2116,1927,2243\" href=\"#F23\">\n<area shape=\"rect\" coor"
    +"ds=\"371,2255,1945,2367\" href=\"#F24\">\n<area shape=\"rect"
    +"\" coords=\"371,2380,1962,2489\" href=\"#F25\">\n<area shape"
    +"=\"rect\" coords=\"368,2506,537,2590\" href=\"#F26\">\n<area"
    +" shape=\"rect\" coords=\"369,2613,1922,2723\" href=\"#F27\">"
    +"\n<area shape=\"rect\" coords=\"367,2756,691,2862\" href=\"#"
    +"F28\">\n<area shape=\"poly\" coords=\"691,2861,721,2797,814,"
    +"2778,1015,2788,1015,2864\" href=\"#F29\">\n<area shape=\"rec"
    +"t\" coords=\"1837,2781,1891,2837\" href=\"#F32\">\n<area sha"
    +"pe=\"rect\" coords=\"427,2986,526,3077\" href=\"#F34\">\n<ar"
    +"ea shape=\"rect\" coords=\"573,3004,1890,3075\" href=\"#F36\""
    +">\n<area shape=\"rect\" coords=\"354,3115,1451,3220\" href="
    +"\"#F37\">\n<area shape=\"poly\" coords=\"1471,3203,1489,3146"
    +",1728,3151,1766,3131,1785,3151,1917,3159,1905,3228,1476,3208"
    +",1471,3206\" href=\"#F39\">\n<area shape=\"rect\" coords=\"3"
    +"53,3240,1422,3359\" href=\"#F40\">\n<area shape=\"rect\" coo"
    +"rds=\"1018,2774,1049,2842\" href=\"#F41\">\n<area shape=\"po"
    +"ly\" coords=\"1051,2849,1049,2778,1189,2790,1317,2785,1383,2"
    +"802,1383,2846,1382,2845\" href=\"#F42\">\n</map>";
    static String IMAGEMAP_A =
    "<div id=\"wrapper\"><img id=\"facsimile\" src=\"/images/front"
    +"ispiece3.jpg\" width=\"2513\" height=\"3701\" border=\"0\" u"
    +"semap=\"#frontispiece3\"></div>\n<map id=\"facsimileMap\" na"
    +"me=\"frontispiece3\">\n<area shape=\"rect\" coords=\"986,397"
    +",1335,494\" href=\"#F1\">\n<area shape=\"rect\" coords=\"434"
    +",637,1476,783\" href=\"#F2\">\n<area shape=\"rect\" coords=\""
    +"1568,637,1937,783\" href=\"#F4\">\n<area shape=\"rect\" coo"
    +"rds=\"371,783,1960,893\" href=\"#F5\">\n<area shape=\"rect\""
    +" coords=\"371,893,1970,1006\" href=\"#F6\">\n<area shape=\"r"
    +"ect\" coords=\"371,1022,1965,1126\" href=\"#F7\">\n<area sha"
    +"pe=\"rect\" coords=\"370,1153,1958,1252\" href=\"#F8\">\n<ar"
    +"ea shape=\"rect\" coords=\"371,1275,1799,1376\" href=\"#F9\""
    +">\n<area shape=\"rect\" coords=\"371,1392,1950,1510\" href=\""
    +"#F10\">\n<area shape=\"rect\" coords=\"369,1520,1950,1632\""
    +" href=\"#F11\">\n<area shape=\"rect\" coords=\"365,1641,1584"
    +",1740\" href=\"#F12\">\n<area shape=\"rect\" coords=\"368,17"
    +"65,1938,1881\" href=\"#F14\">\n<area shape=\"rect\" coords=\""
    +"368,1889,990,1987\" href=\"#F15\">\n<area shape=\"rect\" co"
    +"ords=\"435,2014,658,2102\" href=\"#F17\">\n<area shape=\"rec"
    +"t\" coords=\"651,2004,747,2050\" href=\"#F18\">\n<area shape"
    +"=\"poly\" coords=\"677,2054,678,2101,1490,2102,1488,2029,769"
    +",2027,753,2052\" href=\"#F19\">\n<area shape=\"rect\" coords"
    +"=\"1491,2011,1823,2047\" href=\"#F21\">\n<area shape=\"rect\""
    +" coords=\"1829,2015,1924,2101\" href=\"#F22\">\n<area shape"
    +"=\"rect\" coords=\"372,2116,1927,2243\" href=\"#F23\">\n<are"
    +"a shape=\"rect\" coords=\"371,2255,1945,2367\" href=\"#F24\""
    +">\n<area shape=\"rect\" coords=\"371,2380,1962,2489\" href=\""
    +"#F25\">\n<area shape=\"rect\" coords=\"368,2506,537,2590\" "
    +"href=\"#F26\">\n<area shape=\"rect\" coords=\"369,2613,1922,"
    +"2723\" href=\"#F27\">\n<area shape=\"rect\" coords=\"367,275"
    +"6,691,2862\" href=\"#F28\">\n<area shape=\"poly\" coords=\"6"
    +"99,2801,701,2733,1023,2735,1023,2785,816,2777,698,2801\" hre"
    +"f=\"#F29\">\n<area shape=\"poly\" coords=\"1037,2733,1538,27"
    +"28,1533,2778,1388,2802,1314,2783,1192,2789,1045,2775\" href="
    +"\"#F30\">\n<area shape=\"rect\" coords=\"1837,2781,1891,2837"
    +"\" href=\"#F32\">\n<area shape=\"rect\" coords=\"374,2878,93"
    +"1,2963\" href=\"#F33\">\n<area shape=\"rect\" coords=\"430,2"
    +"987,573,3077\" href=\"#F36\">\n<area shape=\"rect\" coords=\""
    +"573,3004,1890,3075\" href=\"#F36\">\n<area shape=\"rect\" c"
    +"oords=\"354,3115,1451,3220\" href=\"#F37\">\n<area shape=\"p"
    +"oly\" coords=\"1465,3104,1748,3075,1792,3125,1465,3161\" hre"
    +"f=\"#F38\">\n<area shape=\"poly\" coords=\"1471,3203,1489,31"
    +"46,1728,3151,1766,3131,1785,3151,1917,3159,1905,3228,1476,32"
    +"08,1471,3206\" href=\"#F39\">\n<area shape=\"rect\" coords=\""
    +"353,3240,1422,3359\" href=\"#F40\">\n<area shape=\"rect\" c"
    +"oords=\"1018,2774,1049,2842\" href=\"#F41\">\n<area shape=\""
    +"poly\" coords=\"1388,2845,1390,2806,1533,2778,1889,2788,1885"
    +",2846\" href=\"#F44\"></map>\n";
    static String SELECT_A =
    "<select name=\"version1\" id=\"version1\" onchange=\"do_popup"
    +"1()\" class=\"list\" onchange=\"do_popup1()\"><option title=\"Version base\" value=\""
    +"/introduction/base\" class=\"version-short\">base</option>"	
	+"<option title=\"Version add0\" value=\"/introduction/add0\" "
    +"class=\"version-short\" selected=\"selected\">add0</option></select>";
    static String SELECT_D =
    "<select name=\"version1\" id=\"version1\" onchange=\"do_popup"
    +"1()\" class=\"list\" onchange=\"do_popup1()\"><option title=\"Version base\" value=\""
    +"/introduction/base\" class=\"version-short\" selected=\"selected\">base</option>"	
	+"<option title=\"Version add0\" value=\"/introduction/add0\" "
    +"class=\"version-short\">add0</option></select>";
    static String f1d = 
    "<h3><a id=\"#F1\"><span id=\"F1\">Al lettore.</span></a></h3>"
    +"\n<p class=\"indented\"><span id=\"F2\">Quando l’autore e l’"
    +"editore di questi </span><span id=\"F3\">due</span><span id="
    +"\"F4\"> frammenti mi</span><br>\n<span id=\"F5\">pregarono d"
    +"i scrivere due parole di prefazione per la pre-</span><br>\n"
    +"<span id=\"F6\">sente ristampa destinata ai bibliofili e ai "
    +"curiosi, io fran-</span><br>\n<span id=\"F7\">camente dissi:"
    +" che mi sarebbe parso una bella impertinenza</span><br>\n<sp"
    +"an id=\"F8\">anche il solo pensiero di voler scimmiottare il"
    +" divino Aristofane:</span><br>\n<span id=\"F9\">si figurasse"
    +"ro che cosa dovea parermi l’averlo già fatto!</span></p>\n<p"
    +" class=\"indented\"><span id=\"F10\">Ma l’autore rispose che"
    +" appunto intendeva di esser da me</span><br>\n<span id=\"F11"
    +"\">scusato presso il pubblico di questa sua profanazione imp"
    +"rov-</span><br>\n<span id=\"F12\">visata sotto l’impulso d'u"
    +"na forza irresistibile.</span></p>\n<p class=\"indented\"><s"
    +"pan id=\"F14\">(Oh Dio, la forza irresistibile anche nell’ar"
    +"te! Dove s’andrà</span><br>\n<span id=\"F15\">a finire con e"
    +"ssa?)</span><br>\n<p class=\"indented\"><span id=\"F17\">Alm"
    +"eno,</span><span id=\"F19\"> replicai, avreste voi accarezza"
    +"to</span> <span id=\"F21\">un po’ di più</span> <span id=\"F"
    +"22\">la</span><br>\n<span id=\"F23\">forma! Aristofane, v’in"
    +"segnerebbe il nostro Franchetti che se</span><br>\n<span id="
    +"\"F24\">n'intende meglio di tutti noialtri, Aristofane, anch"
    +"e laddo-</span><br>\n<span id=\"F25\">ve sembra più negletto"
    +" lavorava di fino e limava e rilima-</span><br>\n<span id=\""
    +"F26\">va...</span></p>\n<p class=\"indented\"><span id=\"F27"
    +"\">Bella forza! esclamò l’autore. Ma allora non si trattereb"
    +"be</span><br>\n<span id=\"F28\">più d’una</span><span id=\"F"
    +"29\"> profanazione</span><span id=\"F41\">:</span> <span id="
    +"\"F42\">come io confesso...</span></p>\n<p class=\"indented\""
    +"><span id=\"F34\">Una</span><span id=\"F36\"> osservazione "
    +"che mi chiuse la bocca. E dovrebbe, credo,</span><br>\n<span"
    +" id=\"F37\">chiuderla anche a quelli che, lette</span><span "
    +"id=\"F39\"> le <span class=\"underlined\">Nuove Rane,</span>"
    +"</span><br>\n<span id=\"F40\">ne daranno un giudizio pari al"
    +" mio.</span></p>\n";
    static String f1a = 
    "<h3 name=\"F1\"><span id=\"F1\">Al lettore.</span></h3>\n<p c"
    +"lass=\"indented\"><span onmouseover=\"highlightImage('F2')\""
    +" id=\"F2\">Quando l’autore e l’editore di questi</span> <spa"
    +"n id=\"F4\">frammenti mi</span><br>\n<span id=\"F5\">pregaro"
    +"no di scrivere due parole di prefazione per la pre-</span><b"
    +"r>\n<span id=\"F6\">sente ristampa destinata ai bibliofili e"
    +" ai curiosi, io fran-</span><br>\n<span id=\"F7\">camente di"
    +"ssi: che mi sarebbe parso una bella impertinenza</span><br>\n"
    +"<span id=\"F8\">anche il solo pensiero di voler scimmiottar"
    +"e il divino Aristofane:</span><br>\n<span id=\"F9\">si figur"
    +"assero che cosa dovea parermi l’averlo già fatto!</span></p>"
    +"\n<p class=\"indented\"><span id=\"F10\">Ma l’autore rispose"
    +" che appunto intendeva di esser da me</span><br>\n<span id=\""
    +"F11\">scusato presso il pubblico di questa sua profanazione"
    +" improv-</span><br>\n<span id=\"F12\">visata sotto l’impulso"
    +" d’una forza irresistibile.</span></p>\n<p class=\"indented\""
    +"><span id=\"F14\">(Oh Dio, la forza irresistibile anche nel"
    +"l’arte! Dove s’andrà</span><br>\n<span id=\"F15\">a finire c"
    +"on essa?)</span></p>\n<p class=\"indented\"><span id=\"F17\""
    +">Almeno,</span> <span id=\"F18\">allora</span> <span id=\"F1"
    +"9\">replicai, avreste voi accarezzato</span> <span id=\"F21\""
    +">ancora un tantino</span> <span id=\"F22\">la</span><br>\n<"
    +"span id=\"F23\">forma! Aristofane, v’insegnerebbe il nostro "
    +"Franchetti che se</span><br>\n<span id=\"F24\">n’intende meg"
    +"lio di tutti noialtri, Aristofane, anche laddo-</span><br>\n"
    +"<span id=\"F25\">ve sembra più negletto lavorava di fino e l"
    +"imava e rilima-</span><br>\n<span id=\"F26\">va...</span></p"
    +">\n<p class=\"indented\"><span id=\"F27\">Bella forza! escla"
    +"mò l’autore. Ma allora non si tratterebbe</span><br>\n<span "
    +"id=\"F28\">più d’una</span> <span id=\"F29\">scimmiottatura<"
    +"/span><span id=\"F41\">:</span> <span id=\"F30\">anzi d’una "
    +"specie di</span> <span id=\"F44\">profanazione come io</span"
    +"><br>\n<span id=\"F33\">stesso l’ho chiamata.</span></p>\n<p"
    +" class=\"indented\"><span id=\"F35\">Quest’</span> <span id="
    +"\"F36\">osservazione che mi chiuse la bocca. E dovrebbe, cre"
    +"do,</span><br>\n<span id=\"F37\">chiuderla anche a quelli ch"
    +"e, lette</span> <span id=\"F38\">i lei frammenti delle</span"
    +"> <span id=\"F39\" class=\"underlined\">Nuove Rane,</span><b"
    +"r>\n<span id=\"F40\">ne daranno un giudizio pari al mio.</sp"
    +"an></p>\n";
    static String IMAGE_CSS = 
    "div#twinCentreColumn \n{ \n\tborder: 0; \n\tposition: relativ"
    +"e; \n\theight: 1000px; \n\ttop: 0px; \n\tbackground-color: w"
    +"hite; \n\twidth: 80%; \n\tmargin-left: auto; \n\tmargin-righ"
    +"t: auto; \n\ttext-align: left \n}\ndiv#leftColumn \n{\n\tbac"
    +"kground-color: white; \n\tfloat: left; \n\tposition: relativ"
    +"e;\n\tleft: auto; \n\tmargin-right: 5px;\n\tpadding: 10px;\n"
    +"\twidth: 45%;\n\toverflow-y: auto;\n\toverflow-x: auto;\n}\n"
    +"div#rightColumn \n{\n\tbackground-color: white; \n\tfloat: r"
    +"ight; \n\tright: auto; \n\tmargin-left: 5px;\n\tpadding: 10p"
    +"x;\n\twidth: 45%;\n\toverflow-y: auto;\n\toverflow-x: auto;\n"
    +"}\ndiv#buttons\n{\n\tposition:absolute;\n\tbottom:10px;\n\t"
    +"left:10px;\n\twidth:60px;\n\theight:25px;\n\tborder: black 1"
    +"px solid;\n\tbox-shadow: 3px 3px 4px #000;\n\tbackground-col"
    +"or: grey;\n\topacity: 0.5;\n\tborder-radius: 5px;\n}\ndiv#wr"
    +"apper\n{\n\tposition: relative;\n}\np.indented { text-indent"
    +":25px; }\nspan.underlined {text-decoration:underline}\nh3 { "
    +"text-align: center }\narea:hover { background-color: red }";
    static String MAPHILITE =
    "(function(b){var k=!!document.createElement(\"canvas\").getCo"
    +"ntext;if(k){var n=function(d){return Math.max(0,Math.min(par"
    +"seInt(d,16),255))},p=function(d,a){return\"rgba(\"+n(d.subst"
    +"r(0,2))+\",\"+n(d.substr(2,2))+\",\"+n(d.substr(4,2))+\",\"+"
    +"a+\")\"},q=function(d){var a=document.createElement(\"canvas"
    +"\");a.width=d.width;a.height=d.height;null==d.previousSiblin"
    +"g?d.parentNode.insertBefore(a,d):d.parentNode.replaceChild(a"
    +",d.previousSibling);a.getContext(\"2d\").clearRect(0,0,a.wid"
    +"th,a.height);return a},j=function(d,\na,b,e,c){e=e||0;c=c||0"
    +";d.beginPath();if(\"rect\"==a)d.rect(b[0]+e,b[1]+c,b[2]-b[0]"
    +",b[3]-b[1]);else if(\"poly\"==a){d.moveTo(b[0]+e,b[1]+c);for"
    +"(i=2;i<b.length;i+=2)d.lineTo(b[i]+e,b[i+1]+c)}else\"circ\"="
    +"=a&&d.arc(b[0]+e,b[1]+c,b[2],0,2*Math.PI,!1);d.closePath()},"
    +"l=function(d,a,f,e){var c=d.getContext(\"2d\");if(e.shadow){"
    +"c.save();\"inside\"==e.shadowPosition&&(j(c,a,f),c.clip());v"
    +"ar g=100*d.width,h=100*d.height;j(c,a,f,g,h);c.shadowOffsetX"
    +"=e.shadowX-g;c.shadowOffsetY=e.shadowY-h;c.shadowBlur=e.shad"
    +"owRadius;\nc.shadowColor=p(e.shadowColor,e.shadowOpacity);(g"
    +"=e.shadowFrom)||(g=\"outside\"==e.shadowPosition?\"fill\":\""
    +"stroke\");\"stroke\"==g?(c.strokeStyle=\"rgba(0,0,0,1)\",c.s"
    +"troke()):\"fill\"==g&&(c.fillStyle=\"rgba(0,0,0,1)\",c.fill("
    +"));c.restore();\"outside\"==e.shadowPosition&&(c.save(),j(c,"
    +"a,f),c.globalCompositeOperation=\"destination-out\",c.fillSt"
    +"yle=\"rgba(0,0,0,1);\",c.fill(),c.restore())}c.save();j(c,a,"
    +"f);e.fill&&(c.fillStyle=p(e.fillColor,e.fillOpacity),c.fill("
    +"));e.stroke&&(c.strokeStyle=p(e.strokeColor,e.strokeOpacity)"
    +",\nc.lineWidth=e.strokeWidth,c.stroke());c.restore();e.fade&"
    +"&b(d).css(\"opacity\",0).animate({opacity:1},100)},r=functio"
    +"n(d){d.getContext(\"2d\").clearRect(0,0,d.width,d.height);b."
    +"fn.maphilite.inFocus&&b.fn.maphilite.mouseLeave&&(b.fn.maphi"
    +"lite.mouseLeave(b.fn.maphilite.inFocus),b.fn.maphilite.inFoc"
    +"us=null)},s=function(b){var a,f=b.getAttribute(\"coords\").s"
    +"plit(\",\");for(a=0;a<f.length;a++)f[a]=parseFloat(f[a]);ret"
    +"urn[b.getAttribute(\"shape\").toLowerCase().substr(0,4),f]},"
    +"m=function(d,a){var f=b(d);return b.extend({},\na,b.metadata"
    +"?f.metadata():!1,f.data(\"maphilite\"))},t={position:\"absol"
    +"ute\",left:0,top:0,padding:0,border:0};b.fn.maphilite=functi"
    +"on(d){d=b.extend({},b.fn.maphilite.defaults,d);d.mouseEnter&"
    +"&(b.fn.maphilite.mouseEnter=d.mouseEnter);d.mouseLeave&&(b.f"
    +"n.maphilite.mouseLeave=d.mouseLeave);if(this.length)return t"
    +"his.each(function(){var a,f,e,c,g,h,j;e=b(this);b.fn.maphili"
    +"te.img=this;a=\"undefined\"!=typeof this.naturalWidth&&0===t"
    +"his.naturalWidth?!1:!0;if(!a)return window.setTimeout(functi"
    +"on(){e.maphilite(d)},\n200);f=b.extend({},d,b.metadata?e.met"
    +"adata():!1,e.data(\"maphilite\"));a=e.get(0).getAttribute(\""
    +"usemap\");g=b('map[name=\"'+a.substr(1)+'\"]');e.is('img,inp"
    +"ut[type=\"image\"]')&&(a&&0<g.size())&&(e.hasClass(\"maphili"
    +"teed\")&&(a=e.parent(),e.insertBefore(a),a.remove(),b(g).unb"
    +"ind(\".maphilite\").find(\"area[coords]\").unbind(\".maphili"
    +"te\")),a=b(\"<div></div>\").css({display:\"block\",position:"
    +"\"relative\",padding:0,width:this.width,height:this.height,o"
    +"verflow:\"auto\",background:'url(\"'+this.src+'\")',\"backgr"
    +"ound-size\":this.width,\n\"background-repeat\":\"no-repeat\""
    +",\"background-position\":\"0px 0px\"}),f.wrapClass&&(!0===f."
    +"wrapClass?a.addClass(b(this).attr(\"class\")):a.addClass(f.w"
    +"rapClass)),e.before(a).css(\"opacity\",0).css(t).remove(),a."
    +"append(e),c=q(this),b.fn.maphilite.canvas=c,b(c).css(t),c.he"
    +"ight=this.height,c.width=this.width,j=function(a){area_optio"
    +"ns=m(this,f);b.fn.maphilite.img.width!=c.width&&(c=q(b.fn.ma"
    +"philite.img),b.fn.maphilite.canvas=c);shape=s(a);l(b.fn.maph"
    +"ilite.canvas,shape[0],shape[1],area_options,\"highlighted\")"
    +";\nif(a=b(a).attr(\"href\"))b.fn.maphilite.mouseEnter&&(a=a."
    +"substr(1),b.fn.maphilite.mouseEnter(a)),b.fn.maphilite.inFoc"
    +"us=a},b.fn.maphilite.hiliteArea=j,a=function(){var a;a=m(thi"
    +"s,f);if(!a.neverOn&&!a.alwaysOn&&(j(this,a),a.groupBy)){var "
    +"e=this;(/^[a-zA-Z][\\-a-zA-Z]+$/.test(a.groupBy)?g.find(\"ar"
    +"ea[\"+a.groupBy+'=\"'+b(this).attr(a.groupBy)+'\"]'):g.find("
    +"a.groupBy)).each(function(){if(this!=e){var a=m(this,f);if(!"
    +"a.neverOn&&!a.alwaysOn){var b=s(this);l(c,b[0],b[1],a,\"high"
    +"lighted\")}}})}},b.fn.maphilite.clearArea=\nfunction(){r(c)}"
    +",b(g).bind(\"alwaysOn.maphilite\",function(){h&&r(h);k||b(c)"
    +".empty();b(g).find(\"area[coords]\").each(function(){var a,d"
    +";d=m(this,f);d.alwaysOn&&(!h&&k&&(h=q(e[0]),b(h).css(t),h.wi"
    +"dth=e[0].width,h.height=e[0].height,e.before(h)),d.fade=d.al"
    +"waysOnFade,a=s(this),k?l(h,a[0],a[1],d,\"\"):l(c,a[0],a[1],d"
    +",\"\"))})}),b(g).trigger(\"alwaysOn.maphilite\").find(\"area"
    +"[coords]\").bind(\"mouseover.maphilite\",a).bind(\"mouseout."
    +"maphilite\",function(){r(c)}),e.before(c),e.addClass(\"maphi"
    +"liteed\"))})};b.fn.maphilite.defaults=\n{fill:!0,fillColor:\""
    +"000000\",fillOpacity:0.2,stroke:!0,strokeColor:\"ff0000\",s"
    +"trokeOpacity:1,strokeWidth:1,fade:!0,alwaysOn:!1,neverOn:!1,"
    +"groupBy:!1,wrapClass:!0,mouseEnter:null,mouseLeave:null,shad"
    +"ow:!1,shadowX:0,shadowY:0,shadowRadius:6,shadowColor:\"00000"
    +"0\",shadowOpacity:0.8,shadowPosition:\"outside\",shadowFrom:"
    +"!1}}else b.fn.maphilite=function(){return this}})(jQuery);\n";
    static String MODERNIZR =
    ";window.Modernizr=function(a,b,c){function w(a){i.cssText=a}f"
    +"unction x(a,b){return w(prefixes.join(a+\";\")+(b||\"\"))}fu"
    +"nction y(a,b){return typeof a===b}function z(a,b){return!!~("
    +"\"\"+a).indexOf(b)}function A(a,b){for(var d in a){var e=a[d"
    +"];if(!z(e,\"-\")&&i[e]!==c)return b==\"pfx\"?e:!0}return!1}f"
    +"unction B(a,b,d){for(var e in a){var f=b[a[e]];if(f!==c)retu"
    +"rn d===!1?a[e]:y(f,\"function\")?f.bind(d||b):f}return!1}fun"
    +"ction C(a,b,c){var d=a.charAt(0).toUpperCase()+a.slice(1),e="
    +"(a+\" \"+m.join(d+\" \")+d).split(\" \");return y(b,\"string"
    +"\")||y(b,\"undefined\")?A(e,b):(e=(a+\" \"+n.join(d+\" \")+d"
    +").split(\" \"),B(e,b,c))}var d=\"2.6.2\",e={},f=b.documentEl"
    +"ement,g=\"modernizr\",h=b.createElement(g),i=h.style,j,k={}."
    +"toString,l=\"Webkit Moz O ms\",m=l.split(\" \"),n=l.toLowerC"
    +"ase().split(\" \"),o={},p={},q={},r=[],s=r.slice,t,u={}.hasO"
    +"wnProperty,v;!y(u,\"undefined\")&&!y(u.call,\"undefined\")?v"
    +"=function(a,b){return u.call(a,b)}:v=function(a,b){return b "
    +"in a&&y(a.constructor.prototype[b],\"undefined\")},Function."
    +"prototype.bind||(Function.prototype.bind=function(b){var c=t"
    +"his;if(typeof c!=\"function\")throw new TypeError;var d=s.ca"
    +"ll(arguments,1),e=function(){if(this instanceof e){var a=fun"
    +"ction(){};a.prototype=c.prototype;var f=new a,g=c.apply(f,d."
    +"concat(s.call(arguments)));return Object(g)===g?g:f}return c"
    +".apply(b,d.concat(s.call(arguments)))};return e}),o.backgrou"
    +"ndsize=function(){return C(\"backgroundSize\")};for(var D in"
    +" o)v(o,D)&&(t=D.toLowerCase(),e[t]=o[D](),r.push((e[t]?\"\":"
    +"\"no-\")+t));return e.addTest=function(a,b){if(typeof a==\"o"
    +"bject\")for(var d in a)v(a,d)&&e.addTest(d,a[d]);else{a=a.to"
    +"LowerCase();if(e[a]!==c)return e;b=typeof b==\"function\"?b("
    +"):b,typeof enableClasses!=\"undefined\"&&enableClasses&&(f.c"
    +"lassName+=\" \"+(b?\"\":\"no-\")+a),e[a]=b}return e},w(\"\")"
    +",h=j=null,e._version=d,e._domPrefixes=n,e._cssomPrefixes=m,e"
    +".testProp=function(a){return A([a])},e.testAllProps=C,e}(thi"
    +"s,this.document);";
    static String BUTTONS = 
    "<div id=\"buttons\"><input type=\"button\" title=\"enlarge\" "
    +"onclick=\"enlarge()\" value=\"+\" id=\"enlarge_button\"></in"
    +"put>\n<input type=\"button\" title=\"shrink\" onclick=\"shri"
    +"nk()\" value=\"-\" id=\"shrink_button\"></input></div>";
}
